// src/lib/BackButton.svelte
<script>
  export let currentLocation;
  export let updateLocation;

  function goBack() {
    const newLocation = currentLocation.substring(
      0,
      currentLocation.length - 1
    );
    updateLocation(newLocation);
  }
</script>

<button
  class="border px-4 py-2 rounded flex w-auto gap-4 mb-4"
  on:click={goBack}
>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    stroke-width={1.5}
    stroke="currentColor"
    class="w-6 h-6"
  >
    <path
      stroke-linecap="round"
      stroke-linejoin="round"
      d="M10.5 19.5 3 12m0 0 7.5-7.5M3 12h18"
    />
  </svg>
  Retour</button
>

// src/components/BackButton.tsx
interface Props {
  onClick: () => void;
}

const BackButton = ({ onClick }: Props) => {
  return (
    <button className="btn btn-link icon-link mb-2 p-0" onClick={onClick}>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="16"
        height="16"
        fill="currentColor"
        className="bi bi-arrow-left"
        viewBox="0 0 16 16"
      >
        <path
          fillRule="evenodd"
          d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"
        />
      </svg>
      Retour
    </button>
  );
};

export default BackButton;
